import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { ToastContainer } from "react-toastify";
import ProviderWrapper from "./providers";
import './globals.css'
import ToastContainer from "@/component/Toast";
import ConfirmModal from "@/component/ConfirmModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Blogs",
  description: "Generated by My Blogs",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="react-toast mobile:text-lg text-md">
          <ToastContainer />
        </div>
        <div className="min-h-screen bg-gray-50">
          <ProviderWrapper>{children}</ProviderWrapper>
          <ConfirmModal />
        </div>
      </body>
    </html>
  );
}
